export const API_CLIENTS = '';
export const API_PROJECTS = '';
export const API_COMPONENTS = '';
export const API_COMPONENT_BY_ID= '';
export const API_SAVE_INDICATOR = '';
export const EMPTY = '';
export const USER = 'admin';
export const PASS = '';
export const PERCENT = 'PORCENTAJE';
export const REMOVE = 'REMOVE';
export const ADD = 'ADD';
export const INFORMATION = 'INFORMATION';
export const WARNING = 'WARNING';
export const MESSAGE_INDICATORS_SAVED = 'Indicators successfully saved!!';
export const MESSAGE_NO_INDICATORS_TO_SAVE = 'No indicators to save!!'
export const TOKEN = 'token';
export const CLIENT = 'Client';
export const PROJECT = 'Project';